USE securities;

INSERT INTO securities_dict (id, ticker, name, description, type, exchange, sector, lot_size)
VALUES (generateUUIDv4(), 'SBER', 'Сбербанк', 'Крупнейший банк России и Восточной Европы', 'stock', 'MOEX', 'Финансы', 10),
       (generateUUIDv4(), 'GAZP', 'Газпром', 'Крупнейшая газовая компания России', 'stock', 'MOEX', 'Энергетика', 10),
       (generateUUIDv4(), 'LKOH', 'Лукойл', 'Одна из крупнейших нефтегазовых компаний мира', 'stock', 'MOEX', 'Энергетика', 1),
       (generateUUIDv4(), 'TCSG', 'Тинькофф', 'Технологичная финансовая компания', 'stock', 'MOEX', 'Финансы', 1),
       (generateUUIDv4(), 'YNDX', 'Яндекс', 'Крупнейшая российская интернет-компания', 'stock', 'MOEX', 'Информационные технологии', 1),
       (generateUUIDv4(), 'VTBR', 'ВТБ', 'Второй крупнейший банк России', 'stock', 'MOEX', 'Финансы', 100),
       (generateUUIDv4(), 'ROSN', 'Роснефть', 'Крупнейшая российская нефтяная компания', 'stock', 'MOEX', 'Энергетика', 10),
       (generateUUIDv4(), 'SILV', 'Сильвинит', 'Производитель калийных удобрений', 'stock', 'MOEX', 'Химическая промышленность', 100),
       (generateUUIDv4(), 'MTSS', 'МТС', 'Крупнейший российский оператор связи', 'stock', 'MOEX', 'Телекоммуникации', 10),
       (generateUUIDv4(), 'GMKN', 'Норникель', 'Крупнейший производитель палладия и никеля', 'stock', 'MOEX', 'Металлургия', 1),
       (generateUUIDv4(), 'AFLT', 'Аэрофлот', 'Крупнейшая российская авиакомпания', 'stock', 'MOEX', 'Транспорт', 10),
       (generateUUIDv4(), 'SNGS', 'Сургутнефтегаз', 'Одна из крупнейших нефтегазовых компаний', 'stock', 'MOEX', 'Энергетика', 100),
       (generateUUIDv4(), 'TATN', 'Татнефть', 'Нефтяная компания с полным циклом производства', 'stock', 'MOEX', 'Энергетика', 1),
       (generateUUIDv4(), 'ALRS', 'АЛРОСА', 'Крупнейший в мире производитель алмазов', 'stock', 'MOEX', 'Металлургия', 10),
       (generateUUIDv4(), 'MAGN', 'Магнитогорский металлургический комбинат', 'Производитель стали и проката', 'stock', 'MOEX', 'Металлургия', 100),
       (generateUUIDv4(), 'PLZL', 'Полюс Золото', 'Крупнейший производитель золота в России', 'stock', 'MOEX', 'Металлургия', 10),
       (generateUUIDv4(), 'NLMK', 'НЛМК', 'Один из крупнейших металлургических комбинатов', 'stock', 'MOEX', 'Металлургия', 100),
       (generateUUIDv4(), 'SIBN', 'Газпром нефть', 'Вертикально интегрированная нефтяная компания', 'stock', 'MOEX', 'Энергетика', 100),
       (generateUUIDv4(), 'BSPB', 'Банк Санкт-Петербург', 'Региональный банк', 'stock', 'MOEX', 'Финансы', 100),
       (generateUUIDv4(), 'OZON', 'Ozon Holdings', 'Крупнейший интернет-ритейлер', 'stock', 'MOEX', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'WELT', 'Welt', 'Застройщик премиум-класса', 'stock', 'MOEX', 'Строительство', 100),
       (generateUUIDv4(), 'PIK', 'ПИК', 'Крупнейший застройщик России', 'stock', 'MOEX', 'Строительство', 10),
       (generateUUIDv4(), 'MRKK', 'Мираторг', 'Агропромышленный холдинг', 'stock', 'SPB', 'Потребительский сектор', 100),
       (generateUUIDv4(), 'RUAL', 'РУСАЛ', 'Производитель алюминия', 'stock', 'MOEX', 'Металлургия', 100),
       (generateUUIDv4(), 'SBERB1', 'Сбербанк БО-001P-07', 'Облигации Сбербанка серии 07', 'bond', 'MOEX', 'Финансы', 1000),
       (generateUUIDv4(), 'SBERB2', 'Сбербанк БО-002P-08', 'Облигации Сбербанка серии 08', 'bond', 'MOEX', 'Финансы', 1000),
       (generateUUIDv4(), 'GAZPB1', 'Газпром БО-001P-23', 'Облигации Газпрома серии 23', 'bond', 'MOEX', 'Энергетика', 1000),
       (generateUUIDv4(), 'VTBRB1', 'ВТБ БО-001P-15', 'Облигации ВТБ серии 15', 'bond', 'MOEX', 'Финансы', 1000),
       (generateUUIDv4(), 'AFLOTB1', 'Аэрофлот БО-001P-05', 'Облигации Аэрофлота серии 05', 'bond', 'MOEX', 'Транспорт', 1000),
       (generateUUIDv4(), 'LKOH2B1', 'Лукойл БО-001P-02', 'Облигации Лукойл серии 02', 'bond', 'MOEX', 'Энергетика', 1000),
       (generateUUIDv4(), 'TCSGB1', 'Тинькофф БО-002P-09', 'Облигации Тинькофф серии 09', 'bond', 'MOEX', 'Финансы', 1000),
       (generateUUIDv4(), 'MTSSB1', 'МТС БО-001P-32', 'Облигации МТС серии 32', 'bond', 'MOEX', 'Телекоммуникации', 1000),
       (generateUUIDv4(), 'ROSNB1', 'Роснефть БО-001P-18', 'Облигации Роснефти серии 18', 'bond', 'MOEX', 'Энергетика', 1000),
       (generateUUIDv4(), 'PIKB1', 'ПИК БО-001P-04', 'Облигации ПИК серии 04', 'bond', 'MOEX', 'Строительство', 1000),
       (generateUUIDv4(), 'SBMX', 'Сбербанк - Индекс МосБиржи', 'ETF на индекс МосБиржи', 'etf', 'MOEX', 'Финансы', 10),
       (generateUUIDv4(), 'VTBX', 'ВТБ - Индекс РТС', 'ETF на индекс РТС', 'etf', 'MOEX', 'Финансы', 100),
       (generateUUIDv4(), 'TBRU', 'Тинькофф - Индекс МосБиржи', 'ETF на индекс МосБиржи', 'etf', 'MOEX', 'Финансы', 10),
       (generateUUIDv4(), 'SBGB', 'Сбербанк - Гособлигации', 'ETF на государственные облигации', 'etf', 'MOEX', 'Финансы', 10),
       (generateUUIDv4(), 'LQDT', 'ВИМ Ликвидность', 'ETF денежного рынка', 'etf', 'MOEX', 'Финансы', 10),
       (generateUUIDv4(), 'GOLD', 'ВИМ Золото', 'ETF на золото', 'etf', 'MOEX', 'Металлургия', 10),
       (generateUUIDv4(), 'USDRUB', 'ВИМ Доллар', 'ETF на доллар США', 'etf', 'MOEX', 'Финансы', 100),
       (generateUUIDv4(), 'EURRUB', 'ВИМ Евро', 'ETF на евро', 'etf', 'MOEX', 'Финансы', 100),
       (generateUUIDv4(), 'TECH', 'Тинькофф - Технологии', 'ETF на технологический сектор', 'etf', 'MOEX', 'Информационные технологии', 10),
       (generateUUIDv4(), 'DIVD', 'Тинькофф - Дивиденды', 'ETF на дивидендные акции', 'etf', 'MOEX', 'Финансы', 10),
       (generateUUIDv4(), 'AKRN', 'Акрон', 'Производитель минеральных удобрений', 'stock', 'MOEX', 'Химическая промышленность', 10),
       (generateUUIDv4(), 'PHOR', 'ФосАгро', 'Производитель фосфорных удобрений', 'stock', 'MOEX', 'Химическая промышленность', 10),
       (generateUUIDv4(), 'CHMF', 'Северсталь', 'Металлургический и горнодобывающий комбинат', 'stock', 'MOEX', 'Металлургия', 10),
       (generateUUIDv4(), 'TRNFP', 'Транснефть-п', 'Транспортная нефтяная компания (преф)', 'stock', 'MOEX', 'Энергетика', 100),
       (generateUUIDv4(), 'TATNP', 'Татнефть-п', 'Нефтяная компания (преференциальные)', 'stock', 'MOEX', 'Энергетика', 1),
       (generateUUIDv4(), 'SBERP', 'Сбербанк-п', 'Сбербанк (преференциальные)', 'stock', 'MOEX', 'Финансы', 10),
       (generateUUIDv4(), 'MGNT', 'Магнит', 'Розничная торговая сеть', 'stock', 'MOEX', 'Потребительский сектор', 100),
       (generateUUIDv4(), 'BRKL', 'Брокеркредитсервис', 'Финансовая компания', 'stock', 'MOEX', 'Финансы', 1000),
       (generateUUIDv4(), 'ETLN', 'Эталон', 'Застройщик жилой недвижимости', 'stock', 'MOEX', 'Строительство', 100),
       (generateUUIDv4(), 'RSTI', 'Рости Агро', 'Агропромышленная компания', 'stock', 'SPB', 'Потребительский сектор', 10),
       (generateUUIDv4(), 'AAPL', 'Apple Inc.', 'Technology company - iPhone, Mac, iPad', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'MSFT', 'Microsoft Corporation', 'Software and cloud services', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'GOOGL', 'Alphabet Inc.', 'Search engine and digital advertising', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'AMZN', 'Amazon.com Inc.', 'E-commerce and cloud computing', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'NVDA', 'NVIDIA Corporation', 'Graphics processors and AI chips', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'META', 'Meta Platforms Inc.', 'Social media and VR technology', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'TSLA', 'Tesla Inc.', 'Electric vehicles and clean energy', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'NFLX', 'Netflix Inc.', 'Streaming entertainment service', 'stock', 'SPB', 'Телекоммуникации', 1),
       (generateUUIDv4(), 'AMD', 'Advanced Micro Devices', 'Semiconductor company', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'INTC', 'Intel Corporation', 'Semiconductor chip manufacturer', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'JPM', 'JPMorgan Chase', 'Investment bank and financial services', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'BAC', 'Bank of America', 'Banking and financial services', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'WFC', 'Wells Fargo', 'Diversified financial services', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'GS', 'Goldman Sachs', 'Investment banking and securities', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'JNJ', 'Johnson & Johnson', 'Pharmaceuticals and consumer goods', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'UNH', 'UnitedHealth Group', 'Health insurance and healthcare', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'PFE', 'Pfizer Inc.', 'Pharmaceutical corporation', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'MRK', 'Merck & Co.', 'Pharmaceutical company', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'NESN', 'Nestle S.A.', 'Food and beverage company (Switzerland)', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'ASML', 'ASML Holding', 'Semiconductor equipment (Netherlands)', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'NOVN', 'Novartis AG', 'Pharmaceutical company (Switzerland)', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'ROCHE', 'Roche Holding', 'Healthcare company (Switzerland)', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'TM', 'Toyota Motor', 'Automotive manufacturer (Japan)', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'SONY', 'Sony Group', 'Electronics and entertainment (Japan)', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'BABA', 'Alibaba Group', 'E-commerce (China)', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'TCEHY', 'Tencent Holdings', 'Technology conglomerate (China)', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'IRAO', 'Интер РАО', 'Электроэнергетическая компания', 'stock', 'MOEX', 'Энергетика', 100),
       (generateUUIDv4(), 'HYDR', 'РусГидро', 'Гидроэнергетическая компания', 'stock', 'MOEX', 'Энергетика', 100),
       (generateUUIDv4(), 'FEES', 'ФСК ЕЭС', 'Электрические сети', 'stock', 'MOEX', 'Энергетика', 1000),
       (generateUUIDv4(), 'MRKH', 'МРСК Холдинг', 'Распределительные сети', 'stock', 'MOEX', 'Энергетика', 100),
       (generateUUIDv4(), 'AQUA', 'РусАква', 'Водоснабжение и водоотведение', 'stock', 'MOEX', 'Другое', 100),
       (generateUUIDv4(), 'KMAZ', 'КАМАЗ', 'Производитель грузовых автомобилей', 'stock', 'MOEX', 'Другое', 100),
       (generateUUIDv4(), 'NAUK', 'Наука и Инновации', 'Научно-производственная компания', 'stock', 'SPB', 'Информационные технологии', 10),
       (generateUUIDv4(), 'CHMFB1', 'Северсталь БО-001P-12', 'Облигации Северсталь серии 12', 'bond', 'MOEX', 'Металлургия', 1000),
       (generateUUIDv4(), 'YNDXB1', 'Яндекс БО-001P-06', 'Облигации Яндекс серии 06', 'bond', 'MOEX', 'Информационные технологии', 1000),
       (generateUUIDv4(), 'OZONB1', 'Ozon БО-001P-03', 'Облигации Ozon серии 03', 'bond', 'MOEX', 'Потребительский сектор', 1000),
       (generateUUIDv4(), 'SNGSB1', 'Сургутнефтегаз БО-001P-11', 'Облигации Сургутнефтегаз серии 11', 'bond', 'MOEX', 'Энергетика', 1000),
       (generateUUIDv4(), 'ALRSB1', 'АЛРОСА БО-001P-08', 'Облигации АЛРОСА серии 08', 'bond', 'MOEX', 'Металлургия', 1000),
       (generateUUIDv4(), 'SPY', 'SPDR S&P 500 ETF', 'ETF на индекс S&P 500', 'etf', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'QQQ', 'Invesco QQQ', 'ETF на индекс Nasdaq-100', 'etf', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'VTI', 'Vanguard Total Stock Market', 'ETF на весь рынок США', 'etf', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'ARKK', 'ARK Innovation ETF', 'ETF на инновационные компании', 'etf', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'GLD', 'SPDR Gold Shares', 'ETF на золото', 'etf', 'SPB', 'Металлургия', 1),
       (generateUUIDv4(), 'SLV', 'iShares Silver Trust', 'ETF на серебро', 'etf', 'SPB', 'Металлургия', 1),
       (generateUUIDv4(), 'EWJ', 'iShares MSCI Japan', 'ETF на рынок Японии', 'etf', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'FXI', 'iShares China Large-Cap', 'ETF на крупные компании Китая', 'etf', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'MOEX', 'Тинькофф - Индекс МосБиржи USD', 'ETF на индекс МосБиржи в долларах', 'etf', 'MOEX', 'Финансы', 10),
       (generateUUIDv4(), 'RUBP', 'ВИМ Рубль', 'ETF на рублевую ликвидность', 'etf', 'MOEX', 'Финансы', 100),
       (generateUUIDv4(), 'DSTK', 'Детский Мир', 'Розничная сеть детских товаров', 'stock', 'MOEX', 'Потребительский сектор', 10),
       (generateUUIDv4(), 'LENT', 'Лента', 'Розничная торговая сеть', 'stock', 'MOEX', 'Потребительский сектор', 10),
       (generateUUIDv4(), 'X5GR', 'X5 Group', 'Продуктовый ритейл (Пятерочка, Перекресток)', 'stock', 'MOEX', 'Потребительский сектор', 10),
       (generateUUIDv4(), 'FIXP', 'Fix Price', 'Магазин фиксированных цен', 'stock', 'MOEX', 'Потребительский сектор', 10),
       (generateUUIDv4(), 'HEAD', 'Headhunter', 'Платформа для поиска работы', 'stock', 'MOEX', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'IVT', 'Иркут', 'Авиастроительная компания', 'stock', 'MOEX', 'Другое', 10),
       (generateUUIDv4(), 'UACG', 'ОАК', 'Объединенная авиастроительная корпорация', 'stock', 'MOEX', 'Другое', 100),
       (generateUUIDv4(), 'HHRU', 'Хэдхантер', 'HR-технологии', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'VKCO', 'VK Company', 'Интернет-компания (ВКонтакте, OK)', 'stock', 'MOEX', 'Информационные технологии', 10),
       (generateUUIDv4(), 'GROUP', 'Группа ЛСР', 'Застройщик и производитель стройматериалов', 'stock', 'MOEX', 'Строительство', 10),
       (generateUUIDv4(), 'CRM', 'Salesforce', 'CRM software company', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'ORCL', 'Oracle Corporation', 'Database and cloud services', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'IBM', 'IBM Corporation', 'IT consulting and hardware', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'CSCO', 'Cisco Systems', 'Networking hardware', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'ADBE', 'Adobe Inc.', 'Creative software', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'PYPL', 'PayPal Holdings', 'Digital payments', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'SQ', 'Block Inc.', 'Financial services and payments', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'SHOP', 'Shopify Inc.', 'E-commerce platform', 'stock', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'UBER', 'Uber Technologies', 'Ride-sharing and delivery', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'ABNB', 'Airbnb Inc.', 'Online marketplace for lodging', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'MS', 'Morgan Stanley', 'Investment bank', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'C', 'Citigroup Inc.', 'Banking and financial services', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'AXP', 'American Express', 'Financial services corporation', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'BLK', 'BlackRock Inc.', 'Investment management', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'SCHW', 'Charles Schwab', 'Brokerage and banking', 'stock', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'ABBV', 'AbbVie Inc.', 'Biopharmaceutical company', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'TMO', 'Thermo Fisher Scientific', 'Life sciences company', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'DHR', 'Danaher Corporation', 'Life sciences and diagnostics', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'BMY', 'Bristol-Myers Squibb', 'Pharmaceutical company', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'LLY', 'Eli Lilly and Company', 'Pharmaceutical company', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'WMT', 'Walmart Inc.', 'Retail corporation', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'PG', 'Procter & Gamble', 'Consumer goods corporation', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'KO', 'Coca-Cola Company', 'Beverage company', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'PEP', 'PepsiCo Inc.', 'Food and beverage company', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'MCD', 'McDonalds Corporation', 'Fast food restaurant', 'stock', 'SPB', 'Потребительский сектор', 1),
       (generateUUIDv4(), 'DIS', 'Walt Disney Company', 'Entertainment conglomerate', 'stock', 'SPB', 'Телекоммуникации', 1),
       (generateUUIDv4(), 'BA', 'Boeing Company', 'Aerospace manufacturer', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'CAT', 'Caterpillar Inc.', 'Construction and mining equipment', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'GE', 'General Electric', 'Conglomerate corporation', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'MMM', '3M Company', 'Conglomerate corporation', 'stock', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'MGNTB1', 'Магнит БО-001P-07', 'Облигации Магнит серии 07', 'bond', 'MOEX', 'Потребительский сектор', 1000),
       (generateUUIDv4(), 'LENTB1', 'Лента БО-001P-04', 'Облигации Лента серии 04', 'bond', 'MOEX', 'Потребительский сектор', 1000),
       (generateUUIDv4(), 'VKOB1', 'VK БО-001P-02', 'Облигации VK серии 02', 'bond', 'MOEX', 'Информационные технологии', 1000),
       (generateUUIDv4(), 'KMAZB1', 'КАМАЗ БО-001P-09', 'Облигации КАМАЗ серии 09', 'bond', 'MOEX', 'Другое', 1000),
       (generateUUIDv4(), 'AQUAB1', 'РусАква БО-001P-03', 'Облигации РусАква серии 03', 'bond', 'MOEX', 'Другое', 1000),
       (generateUUIDv4(), 'XLF', 'Financial Select Sector SPDR', 'ETF на финансовый сектор США', 'etf', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'XLK', 'Technology Select Sector SPDR', 'ETF на технологический сектор США', 'etf', 'SPB', 'Информационные технологии', 1),
       (generateUUIDv4(), 'XLV', 'Health Care Select Sector SPDR', 'ETF на сектор здравоохранения', 'etf', 'SPB', 'Другое', 1),
       (generateUUIDv4(), 'XLE', 'Energy Select Sector SPDR', 'ETF на энергетический сектор', 'etf', 'SPB', 'Энергетика', 1),
       (generateUUIDv4(), 'EEM', 'iShares MSCI Emerging Markets', 'ETF на развивающиеся рынки', 'etf', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'VEA', 'Vanguard FTSE Developed Markets', 'ETF на развитые рынки', 'etf', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'IWM', 'iShares Russell 2000', 'ETF на малые компании США', 'etf', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'DIA', 'SPDR Dow Jones Industrial Average', 'ETF на индекс Dow Jones', 'etf', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'VWO', 'Vanguard FTSE Emerging Markets', 'ETF на развивающиеся рынки', 'etf', 'SPB', 'Финансы', 1),
       (generateUUIDv4(), 'EFA', 'iShares MSCI EAFE', 'ETF на Европу, Австралию и Дальний Восток', 'etf', 'SPB', 'Финансы', 1);
