ktor {
  application {
    modules = [zov.deneg.ApplicationKt.module]
  }
  deployment {
    port = 8080
  }
}

jwt {
  audience = ${JWT_AUDIENCE}
  issuer = ${JWT_ISSUER}
  realm = ${?JWT_REALM}"zov-deneg"
  secret = ${JWT_SECRET}
  accessTokenTtlSeconds = ${JWT_ACCESS_TTL_SEC}
  refreshTokenTtlDays = ${JWT_REFRESH_TTL_DAYS}
}

postgres {
  url = "jdbc:postgresql://"${POSTGRES_HOST}":"${POSTGRES_PORT}"/"${POSTGRES_DB}
  user = ${POSTGRES_USER}
  password = ${POSTGRES_PASSWORD}
  driver = "org.postgresql.Driver"
}

h2 {
  url = "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
  user = "root"
  password = ""
  driver = "org.h2.Driver"
}

database {
  useEmbedded = ${?DATABASE_USE_EMBEDDED}false
}

securities-service {
  baseUrl = ${?SECURITIES_SERVICE_URL}"http://zov-securities-service:8080"
  connectTimeout = ${?SECURITIES_SERVICE_CONNECT_TIMEOUT}5000
  requestTimeout = ${?SECURITIES_SERVICE_REQUEST_TIMEOUT}10000
  maxConnections = ${?SECURITIES_SERVICE_MAX_CONNECTIONS}10
}
