ktor:
    application:
        modules:
            - zov.deneg.ApplicationKt.module
    deployment:
        port: 8080

jwt:
    audience: ${JWT_AUDIENCE}
    issuer: ${JWT_ISSUER}
    realm: "zov-deneg"
    secret: ${JWT_SECRET}
    accessTokenTtlSeconds: ${JWT_ACCESS_TTL_SEC}
    refreshTokenTtlDays: ${JWT_REFRESH_TTL_DAYS}

postgres:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    driver: "org.postgresql.Driver"

h2:
    url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
    user: "root"
    password: ""
    driver: "org.h2.Driver"

database:
    useEmbedded: false
